# Generated by Django 3.1.7 on 2021-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210317_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('primary', 'normal'), ('success', 'low')], max_length=50),
        ),
    ]
